"""The default v2.0 claim-mapping config seeded for every test tenant.

Why this exists: the authorizer resolves a principal's Porth roles by running a tenant's
**compiled** claim-mapping. A tenant without one logs
``no claim mapping config for tenant=…; roles will be empty`` and its admin gets no menu —
the PORTH-479 trap. Seeding a tenant without this is seeding a broken tenant.

PORTH-591 — the roles-claim namespace is **per-install** and is derived here, not
hardcoded. The Auth0 post-login Action namespaces its custom claims by the API audience
(``ns = aud``), so the claim arrives as ``<audience>/roles``. The mapping matches the claim
key character-for-character, so a namespace that does not equal the audience means the
claim is never found, roles resolve empty, and the admin gets no menu — with nothing in the
logs saying why. It reads as "no roles assigned" at every layer.

This module previously hardcoded ``https://porth.io/roles``, which is no install's
audience: EMS uses ``https://porth.ems.estynsoftware.io``, elegans-dev uses
``https://porth.elegans-dev.estynsoftware.io``. ``scripts/bootstrap_platform_tenant.py``
was fixed for exactly this and this file was not, so every tenant the testbed seeder has
ever created carries a mapping that silently resolves nothing.

Deriving the value also makes the repair automatic: ``COMPILED_HASH`` is now a hash of the
rendered source, so a tenant seeded under the old namespace has a different hash and the
seeder writes a new version rather than skipping it as already-current.

The compiled artifact is rendered from a template rather than compiled at runtime, so this
Lambda still needs no ``porth_common`` dependency.
"""
from __future__ import annotations

import hashlib
import json
import os

import boto3

#: Placeholder substituted in the compiled template. Not a valid claim key on purpose —
#: if one ever reaches DynamoDB, it is unmistakably a rendering bug rather than a
#: plausible-looking wrong namespace that fails silently.
_PLACEHOLDER = "__ROLES_CLAIM__"

_COMPILED_TEMPLATE = (
    "# AUTO-GENERATED by claim_mapping_codegen — config hash c9845fb83254fbc8\n"
    "# DO NOT EDIT manually. Re-generate from the mapping config.\n"
    "from __future__ import annotations\n"
    "from typing import Any\n"
    "from porth_common.services.exceptions import MappingError\n"
    "\n"
    "def _get_path(obj: dict, path: str) -> Any:\n"
    '    """OIDC-aware dot-notation path resolver."""\n'
    "    if not isinstance(obj, dict) or not path:\n"
    "        return None\n"
    '    if path.startswith(("http://", "https://")):\n'
    "        return obj.get(path)\n"
    '    parts = path.split(".")\n'
    "    current: Any = obj\n"
    "    for part in parts:\n"
    "        if not isinstance(current, dict):\n"
    "            return None\n"
    "        current = current.get(part)\n"
    "        if current is None:\n"
    "            return None\n"
    "    return current\n"
    "\n"
    "def map_claims(claims: dict, role_registry: dict | None = None) -> dict:\n"
    '    """Map JWT claims to user model fields.\n'
    "    \n"
    "    Args:\n"
    "        claims: Raw JWT claims dict from identity provider.\n"
    "        role_registry: Optional dict mapping source_key values to role IDs.\n"
    "            Required for fields with resolve_roles op.\n"
    "    Returns:\n"
    "        Dict of {field_name: transformed_value}.\n"
    "    Raises:\n"
    "        MappingError: If a required claim is absent.\n"
    '    """\n'
    "    result: dict = {}\n"
    "\n"
    "    # field: roles (collection)\n"
    f"    _v = claims.get('{_PLACEHOLDER}')\n"
    "    if _v is not None:\n"
    "        if not isinstance(_v, list):\n"
    "            _v = [_v]\n"
    "        _collection = []\n"
    "        for _elem in _v:\n"
    "            _ev = _elem\n"
    "            # resolve_roles: match against role registry\n"
    "            if _ev is not None and role_registry is not None:\n"
    "                _ev = role_registry.get(str(_ev))\n"
    "            if _ev is not None:\n"
    "                _collection.append(_ev)\n"
    "        result['roles'] = list(dict.fromkeys(_collection))\n"
    "\n"
    "    return result\n"
)


def roles_namespace() -> str:
    """The claim key this install's Action writes roles under.

    Precedence mirrors ``scripts/bootstrap_platform_tenant.py`` so the two seeders cannot
    disagree: an explicit override, then an explicit audience, then the ``/porth/auth``
    blob the proxy and authorizer already read — one source of truth rather than a second
    value to keep in step.

    Raises rather than falling back to a default. A wrong namespace produces a tenant that
    looks correctly seeded and resolves no roles; failing the seed is loud, and loud is
    the only version of this anyone notices.
    """
    explicit = os.environ.get("PORTH_ROLES_NAMESPACE", "").strip()
    if explicit:
        return explicit

    audience = os.environ.get("PORTH_AUTH_AUDIENCE", "").strip()
    if not audience:
        blob = boto3.client("ssm").get_parameter(
            Name=os.environ.get("PORTH_AUTH_PARAMETER", "/porth/auth"),
            WithDecryption=True,
        )["Parameter"]["Value"]
        audience = (json.loads(blob).get("audience") or "").strip()

    if not audience:
        raise RuntimeError(
            "Cannot derive the roles-claim namespace: no audience in /porth/auth and "
            "neither PORTH_AUTH_AUDIENCE nor PORTH_ROLES_NAMESPACE is set. Refusing to "
            "seed a claim mapping that would silently resolve no roles."
        )
    return f"{audience.rstrip('/')}/roles"


def mapping_source(namespace: str) -> dict:
    """The authored mapping. Descriptive only — the authorizer runs the compiled source."""
    return {
        "schema_version": "2.0",
        "fields": [
            {
                "name": "roles",
                "source": namespace,
                "type": "collection",
                "required": False,
                "ops": [{"op": "resolve_roles"}],
            }
        ],
        "default_roles": [],
    }


def compiled_source(namespace: str) -> str:
    """The artifact the authorizer actually executes."""
    rendered = _COMPILED_TEMPLATE.replace(_PLACEHOLDER, namespace)
    if _PLACEHOLDER in rendered:  # pragma: no cover - defensive
        raise RuntimeError("claim-mapping template was not fully rendered")
    return rendered


def compiled_hash(source: str) -> str:
    """Hash of the rendered source.

    This is the cache key ``claim_mapping_cache`` uses, so it must change whenever the
    source does — otherwise a warm authorizer keeps executing bytecode it compiled from
    the previous version. Deriving it from the source makes that automatic.
    """
    return hashlib.sha256(source.encode()).hexdigest()


def resolved() -> tuple[dict, str, str]:
    """``(mapping_source, compiled_source, compiled_hash)`` for this install."""
    ns = roles_namespace()
    src = compiled_source(ns)
    return mapping_source(ns), src, compiled_hash(src)
