"""The default v2.0 claim-mapping config seeded for every test tenant.

Why this exists: the authorizer resolves a principal's Porth roles by running a tenant's
**compiled** claim-mapping. A tenant without one logs
``no claim mapping config for tenant=…; roles will be empty`` and its admin gets no menu —
the PORTH-479 trap. Seeding a tenant without this is seeding a broken tenant.

The mapping is identical to the one the platform tenant gets (`reset-env.yml`): resolve the
IdP's ``https://porth.io/roles`` claim against the tenant's role registry. Nothing here is
tenant-specific, so the same compiled artifact is written under each tenant's partition.

``COMPILED_SOURCE`` is pre-generated by ``MappingCodegen.generate(MAPPING_SOURCE)`` — it is not
compiled at runtime, so this Lambda needs no porth_common dependency. If ``MAPPING_SOURCE``
changes, regenerate both the source and the hash.
"""
from __future__ import annotations

MAPPING_SOURCE = {
    "schema_version": "2.0",
    "fields": [
        {
            "name": "roles",
            "source": "https://porth.io/roles",
            "type": "collection",
            "required": False,
            "ops": [{"op": "resolve_roles"}],
        }
    ],
    "default_roles": [],
}

COMPILED_SOURCE = (
    "# AUTO-GENERATED by claim_mapping_codegen — config hash c9845fb83254fbc8\n"
    "# DO NOT EDIT manually. Re-generate from the mapping config.\n"
    "from __future__ import annotations\n"
    "from typing import Any\n"
    "from porth_common.services.exceptions import MappingError\n"
    "\n"
    "def _get_path(obj: dict, path: str) -> Any:\n"
    '    """OIDC-aware dot-notation path resolver."""\n'
    "    if not isinstance(obj, dict) or not path:\n"
    "        return None\n"
    '    if path.startswith(("http://", "https://")):\n'
    "        return obj.get(path)\n"
    '    parts = path.split(".")\n'
    "    current: Any = obj\n"
    "    for part in parts:\n"
    "        if not isinstance(current, dict):\n"
    "            return None\n"
    "        current = current.get(part)\n"
    "        if current is None:\n"
    "            return None\n"
    "    return current\n"
    "\n"
    "def map_claims(claims: dict, role_registry: dict | None = None) -> dict:\n"
    '    """Map JWT claims to user model fields.\n'
    "    \n"
    "    Args:\n"
    "        claims: Raw JWT claims dict from identity provider.\n"
    "        role_registry: Optional dict mapping source_key values to role IDs.\n"
    "            Required for fields with resolve_roles op.\n"
    "    Returns:\n"
    "        Dict of {field_name: transformed_value}.\n"
    "    Raises:\n"
    "        MappingError: If a required claim is absent.\n"
    '    """\n'
    "    result: dict = {}\n"
    "\n"
    "    # field: roles (collection)\n"
    "    _v = claims.get('https://porth.io/roles')\n"
    "    if _v is not None:\n"
    "        if not isinstance(_v, list):\n"
    "            _v = [_v]\n"
    "        _collection = []\n"
    "        for _elem in _v:\n"
    "            _ev = _elem\n"
    "            # resolve_roles: match against role registry\n"
    "            if _ev is not None and role_registry is not None:\n"
    "                _ev = role_registry.get(str(_ev))\n"
    "            if _ev is not None:\n"
    "                _collection.append(_ev)\n"
    "        result['roles'] = list(dict.fromkeys(_collection))\n"
    "\n"
    "    return result\n"
)

COMPILED_HASH = "55016a468cbb18927879e32725927fc3d501a7887918f05eed50911918fd6855"
